name: 'citus JITSI-MEET custom sdk repo'
description: 'jitsi meet custom sdk by CITUS'
author: 'citus'

jobs:
  # Single deploy job no building
  deploy:
    environment:
      name: jitsi-meet-repo
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # upload entire directory
          path: '.releases/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2